<p>当程序的控制进入一个没有出口的循环时就会发生递归（recursion）。当一个方法调用自身，或是两个方法相互调用，又或是当 <code>goto</code> 语句用于在两段代码间跳转时就可能会发生这种情况。它可以成为一个有用的工具，但除非方法中包含了跳出递归并 <code>return</code> 的规定，否则递归就会一直运行，直到堆栈溢出和程序崩溃。</p>
<h2>不合规的代码示例</h2>
<pre>
int Pow(int num, int exponent)   // 不合规；没有停止调用pow的条件
{
  num = num * Pow(num, exponent-1);
  return num;  // 程序无法执行到这条语句
}

void InternalRecursion(int i)
{
  start:
    goto end;
  end:
    goto start; // 不合规；程序无法跳出这个方法
}
</pre>
<h2>合规的解决方案</h2>
<pre>
int Pow(int num, int exponent)
{
  if (exponent &gt; 1) // 此处使递归变得有条件且可以停止
  {
    num = num * Pow(num, exponent-1);
  }
  return num;
}
</pre>

